baseURL: https://ryanbalshaw.github.io/sjmelck_pages/
languageCode:   en-us
DefaultContentLanguage: en
theme: sjmelck-theme
pluralizeListTitles: false
dark_mode: auto
publishDir: "docs"
summaryLength: 50
title: Sjmelck
enableRobotsTXT: true
enableEmoji: true
googleAnalytics: "G-TZK5KHZQ8Y"
params:
  AuthorName: Ryan Balshaw
  GitHubUser: RyanBalshaw
  description: "Sjmelck Just Means Engineers Love Computers K? Sjmelck (Pronounces 100% exaclty like it is written), aims to be the engineers cheat sheet to the world of scientific computing."
sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5
menu:
  main:
    - identifier: about
      name: about
      url: "/about/"
      weight: 10
    - identifier: blog
      name: blog
      url: "/blog/"
      weight: 20
  about:
    - identifier: about-ryan
      name: Contributor - Ryan Balshaw
      url: 'about/ryan-balshaw'
      weight: 30
      params:
        author_name: "ryan"
    - identifier: douw
      name: Contributor - Douw Marx
      url: 'about/douw-marx'
      params:
        author_name: "douw"
    - identifier: johann
      name: Contributor - Johann Bouwer
      url: 'about/johann-bouwer'
      params:
        author_name: "johann"
    - identifier: about-justin
      name: Contributor - Justin Smith
      url: 'about/justin-smith'
      weight: 40
      params:
        author_name: "justin"
    - identifier: about-sjmelck
      name: The Sjmelck vision
      url: 'about/the-origins-of-sjmelck'
  ryan_social:
    - identifier: 'description'
      name: "PhD Candidate at the University of Pretoria"
      weight: 20
    - name: 'Github'
      url: "https://github.com/RyanBalshaw/"
      pre: "<i class='bi bi-github socialIcon'></i>"
    - name: Linkedin
      url: "https://linkedin.com/in/ryan-balshaw/"
      pre: "<i class='bi bi-linkedin socialIcon'></i>"
    - name: Twitter
      url: "https://twitter.com/ryan_balshaw/"
      pre: "<i class='bi bi-twitter socialIcon'></i>"
    - name: Email
      url: "mailto: ryanbalshaw81@gmail.com"
      pre: "<i class='bi bi-envelope-at socialIcon'></i>"
  douw_social:
    - identifier: 'description'
      name: "Research associate at KU Leuven"
      weight: 20
    - name: Github
      url: "https://github.com/DouwMarx/"
      pre: "<i class='bi bi-github socialIcon'></i>"
    - name: Linkedin
      url: "https://linkedin.com/in/douw-marx-913503163/"
      pre: "<i class='bi bi-linkedin socialIcon'></i>"
    - name: Email
      url: "mailto: douwmarx@gmail.com"
      pre: "<i class='bi bi-envelope-at socialIcon'></i>"
  johann_social:
    - identifier: 'description'
      name: "PhD candidate and assistant lecturer at the University of Pretoria"
      weight: 20
    - name: Github
      url: "https://github.com/JohannBouwer/"
      pre: "<i class='bi bi-github socialIcon'></i>"
    - name: Linkedin
      url: "https://www.linkedin.com/in/johann-mynhardt-bouwer-3086a3293/"
      pre: "<i class='bi bi-linkedin socialIcon'></i>"
    - name: Email
      url: "mailto: bouwer2608@gmail.com"
      pre: "<i class='bi bi-envelope-at socialIcon'></i>"
  justin_social:
    - identifier: 'description'
      name: "Masters candidate at the University of Pretoria"
      weight: 30
    - name: Github
      url: "https://github.com/JustinSmith66/"
      pre: "<i class='bi bi-github socialIcon'></i>"
    - name: Linkedin
      url: "https://www.linkedin.com/in/justin-s-507338116/"
      pre: "<i class='bi bi-linkedin socialIcon'></i>"
    - name: Email
      url: "mailto: 66smithjustin@gmail.com"
      pre: "<i class='bi bi-envelope-at socialIcon'></i>"